# Generated by Django 2.1.7 on 2019-03-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_desc',
            field=models.TextField(default=None),
        ),
    ]
