version: '3.3'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '127.0.0.1:3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - db_folder:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpasswd'
      MYSQL_DATABASE: 'newssitedb'
      MYSQL_USER: 'newssiteuser'
      MYSQL_PASSWORD: 'newssitepasswd'
# Names our volume
volumes:
  db_folder:
