version: '3.3'
services:
  db:
    image: mysql:latest
    container_name: mysql_for_newssite
    command: --default-authentication-plugin=mysql_native_password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '127.0.0.1:3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - db_folder:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpasswd'
      MYSQL_DATABASE: 'newssitedb'
      MYSQL_USER: 'newssiteuser'
      MYSQL_PASSWORD: 'newssitepasswd'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch_for_newssite
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
      

# Names our volume
volumes:
  db_folder:
  esdata1:
    driver: local

networks:
  esnet:
